/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainPackage;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author st201518650
 */
public class NotesWindow extends javax.swing.JFrame {
    AddNoteButtonListener listener;
    private NoteAdd noteAddJframe;
    
    // TODO REMOVE STATIC INNIT
    private Paper paper ;    
    public NotesWindow(Paper paper){
    this.paper = paper;
      initComponents();
        createColumns();
        
        populateNotes();
        
        sorter = new TableRowSorter<DefaultTableModel>(dm);
        jTable1.setRowSorter(sorter);
    }
    
    
     DefaultTableModel dm;
     TableRowSorter<DefaultTableModel> sorter;

    private void createColumns() {
        dm = (DefaultTableModel) jTable1.getModel();
        String[] columns = {"#", "Title", "Category", "Date Modified"};
//        jTable1.getColumnModel().getColumn(0).setMinWidth(5);
//        jTable1.getColumnModel().getColumn(0).setMaxWidth(5);
//        jTable1.getColumnModel().getColumn(0).setWidth(5);
        for (String column : columns) {
            dm.addColumn(column);
        }
        
        


    }
    public void populateNotes(){
         dm = (DefaultTableModel) jTable1.getModel();
            dm.setRowCount(0);
            int i=0;
            for(Note note : paper.getNotes()){
                String[] array = note.getTableArray();
             array[0]= i+"";
            
          dm.addRow(array);
           i++;
            }
        }

    public Paper getPapers() {
        return paper;
    }

    public void setPapers(Paper papers) {
        this.paper = papers;
    }

    /**
     * Creates new form NotesWindow
     */
    public NotesWindow() {
        
        
        initComponents();
        createColumns();

        populateNotes();
        
        sorter = new TableRowSorter<DefaultTableModel>(dm);
        jTable1.setRowSorter(sorter);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Note Manager");
        setResizable(false);

        jTable1.setModel(new javax.swing.table.DefaultTableModel()
            {public boolean isCellEditable(int row, int column){return false;}}
        );
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("View/Edit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Add");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(102, 102, 102))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
      
         noteAddJframe = new NoteAdd(paper);
        noteAddJframe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        noteAddJframe.getjButton1().addActionListener(new AddNoteButtonListener());
        noteAddJframe.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       noteAddJframe = new NoteAdd(paper);
       int index = Integer.parseInt((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
       Note selectedNote = paper.getNotes().get(index);     
       noteAddJframe.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
       noteAddJframe.getjButton1().addActionListener(new EditNoteButtonListener());
       noteAddJframe.getjTextArea1().setText(selectedNote.getContent());
       noteAddJframe.getjTextField1().setText(selectedNote.getTitle());
       noteAddJframe.getjTextField2().setText(selectedNote.getKeywords());
       noteAddJframe.setVisible(true);
       
 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                  int index = Integer.parseInt((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                    paper.getNotes().remove(index);
                    populateNotes();
    }//GEN-LAST:event_jButton1ActionPerformed
    class  EditNoteButtonListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           
            int index = Integer.parseInt((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0));
            Note selectedNote = paper.getNotes().set(index, new Note(noteAddJframe.getjTextField1().getText(), paper.getCategory(),noteAddJframe.getjTextArea1().getText(),noteAddJframe.getjTextField2().getText()));
            noteAddJframe.dispose();
            populateNotes();
            System.out.println("XXXXXXXXXXXXXXXXXXXX Edit Notes Performed");
            MainWindow.changed = true;
            
        }
    
    }
    
      class  AddNoteButtonListener implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
           
            paper.getNotes().add(new Note(noteAddJframe.getjTextField1().getText(), paper.getCategory(),noteAddJframe.getjTextArea1().getText(),noteAddJframe.getjTextField2().getText()));
            noteAddJframe.dispose();
            populateNotes();
            System.out.println("XXXXXXXXXXXXXXXXXXXX Add Notes Performed");
            MainWindow.changed = true;
            
        }
    
    }
      
         
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NotesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NotesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NotesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NotesWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NotesWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
